### ISSUE TITLE
include vault id in example

### ISSUE THREAD

**Issue by Iwuaa** [tksh164/aumid-stopgap-tools#16]
Hi, sorry, this is not a bug but I didn't know where else should I post this.

In the example you could mention the option to use [vault id](https://help.obsidian.md/Extending+Obsidian/Obsidian+URI#Examples) URI, which I think is easier to find and fill in correctly.

It's just a number `obsidian://open?vault=ef6ca3e3b524d22f` instead of a formated string and it's easy to get from Obsidian vault menu

![image](https://github.com/user-attachments/assets/ce7fb7e2-9990-4a10-b20c-5ad5028dc1a6)

I really like this program, very useful, good job 👍

**Comment by tksh164** [comment]
Thank you @Iwuaa for your feedback. Your mentioned point added to the README.
